### ISSUE TITLE
Checksum verification

### ISSUE THREAD

**Issue by jdolitsky** [imjasonh/setup-crane#1]
Does it make sense to validate the checksum of release tarballs prior to unpacking?

Maybe as an optional input param?

**Comment by imjasonh** [comment]
Is that something I can get from GitHub? I'd rather not have to maintain a mapping of version->sha myself.

That means a compromised GitHub can lie to us about the artifact and it's sha, but then they could also lie to users about what this action is configured to do, so 🤷‍♂️

**Comment by jdolitsky** [comment]
It's be something as a user I could provide (optionally):
```
- uses: imjasonh/setup-crane@v0.1
  with:
    version: v0.6.0
    checksum: b71c7ca16abff07787516efbe0c06c129d273f34490d6a85f815cec980fffe85
```

Happy to PR this
