### ISSUE TITLE
Github actions setup: jq: command not found

### ISSUE THREAD

**Issue by oerp-odoo** [imjasonh/setup-crane#8]
**Description**

When I run on self hosted runner:
```yaml
  tag:
    runs-on: self-hosted
    needs: project_names_wkf
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.5
      - uses: imjasonh/setup-crane@v0.3
```
I get this error
```
Run imjasonh/setup-crane@v0.3
Run set -ex
+ case latest-release in
++ curl -s -u username:*** https://api.github.com/repos/google/go-containerregistry/releases/latest
++ jq -r .tag_name
/opt/runner/actions-runner/_work/_temp/20dd5098-8b64-49b1-aed9-cdc6841fd792.sh: line 13: jq: command not found
+ tag=
```
I guess it expects `jq` to already be installed?
