### ISSUE TITLE
Github actions setup: a terminal is required to read the password

### ISSUE THREAD

**Issue by oerp-odoo** [imjasonh/setup-crane#9]
**Description**

```yaml
  tag:
    runs-on: self-hosted
    needs: project_names_wkf
    steps:
      - uses: dcarbone/install-jq-action@v1.0.1
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.5
      - uses: imjasonh/setup-crane@v0.3
```
I get this error. Not sure why its asking for a password:

```
Run imjasonh/setup-crane@v0.3
Run set -ex
+ case latest-release in
++ curl -s -u username:*** https://api.github.com/repos/google/go-containerregistry/releases/latest
++ jq -r .tag_name
+ tag=v0.15.2
+ os=Linux
+ [[ Linux == \m\a\c\O\S ]]
++ uname -m
+ arch=x86_64
+ [[ x86_64 =~ (aarch64|arm64) ]]
+ [[ ! -z v0.15.2 ]]
+ echo 'Installing crane @ v0.15.2 for Linux on x86_64'
Installing crane @ v0.15.2 for Linux on x86_64
+ sudo tar xzf - -C /usr/local/bin crane
+ curl -fsL https://github.com/google/go-containerregistry/releases/download/v0.15.2/go-containerregistry_Linux_x86_64.tar.gz
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
Error: Process completed with exit code 1.
```
P.S. Note I am also installing `jq` manually as I get other error during `crane` setup
